### ISSUE TITLE
No Way To Repair Tools&Armors ?

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#93] opened 2017-01-22 15:19 UTC
is there already a way, forgive me. But i tried many ways. Is there? using game 1.11.2 forge 2222

**Comment by sokratis12GR** [comment] 2017-01-22 15:19
have you tried repairing them with their crafting material ?

**Comment by sokratis12GR** [comment] 2017-01-22 15:20
and which gamemode are you using ?

**Comment by sokratis12GR** [comment] 2017-01-22 15:20
because 0 - easy; 1 - expert; 2 - hellish (no way to repair items)

**Comment by ghost** [comment] 2017-01-22 15:52
i tried with crafting material, yes. it didn't work. gamemode? what do you mean? in survival mode i am in? or difficulty? it is normal...

**Comment by sokratis12GR** [comment] 2017-01-22 15:52
I mean config changes

**Comment by ghost** [comment] 2017-01-22 15:55
oh, it is 1

**Comment by ghost** [comment] 2017-01-22 15:55
should i make it 0 ?

**Comment by sokratis12GR** [comment] 2017-01-22 15:56
you shouldn't need to hmm... thats strange

**Comment by ghost** [comment] 2017-01-22 15:56
btw, for example i have superstar battleaxe. i tried wither bone to repair it.(in crafting slots) do i do wrong?

**Comment by sokratis12GR** [comment] 2017-01-22 15:58
yes... you need an anvil

**Comment by ghost** [comment] 2017-01-22 15:58
oh... sorry... i didn't know that.

**Comment by sokratis12GR** [comment] 2017-01-22 15:59
no worries, thanks for you time.

**Comment by ghost** [comment] 2017-01-22 16:00
and ah, forgive me but i just wonder what is the changelog for the new version :D

**Comment by sokratis12GR** [comment] 2017-01-22 16:01
there will be a hot fix because of a bug and the addition of JEI support for the Infuser

**Comment by ghost** [comment] 2017-01-22 16:01
okay, thanks a lot.

**Comment by ghost** [comment] 2017-01-22 16:07
oh, please forgive me but how to repair the item with anvil? i placed the super star battleaxe to the leften slot on anvil, and placed wither bone to the righten slot. but nothing happened. am i wrong again?

**Comment by ghost** [comment] 2017-05-01 15:02
still waiting for help :D can't we repair items on anvil?

**Comment by sokratis12GR** [comment] 2017-05-01 18:52
Armors can be repaired with their crafted materials,
except if config is set to gamemode 2 (hellish)

**Comment by ghost** [comment] 2017-05-01 18:53
weapons?

**Comment by ghost** [comment] 2017-05-01 18:54
it's 1 as default, if i make it 0 can i repair my wepon or armor on crafting or anvil? thanks.

**Comment by sokratis12GR** [comment] 2017-05-01 18:56
armors/weapons anything can be repaired from gamemode 0-1

**Comment by ghost** [comment] 2017-05-01 19:00
then why i can't repair my superstar battleaxe on anvil with wither bone :D

**Comment by sokratis12GR** [comment] 2017-05-01 19:20
:/ It supposed to be repaired with Wither Bones, but I guess, it doesn't work anymore hmm, gonna be fixed soon, hopefully

**Comment by ghost** [comment] 2017-05-01 19:21
^^ i'm waiting this be fixed for months :D

**Comment by sokratis12GR** [comment] 2017-05-01 19:26
sorry, I just never really looked in depth to it... its a problem of how I register them Items... uhm this to be fixed... will require RIPing off all the materials from all worlds

**Comment by sokratis12GR** [comment] 2017-05-01 19:26
currently you can repair it with Guardian scale or Chainmail

**Comment by ghost** [comment] 2017-05-01 19:27
no problem ^^ waiting for the new release

**Comment by sokratis12GR** [comment] 2017-05-01 19:29
The problem is that the new release will be game+world-breaking update... the upcoming versions will be released as ALPHA and won't be stable at all, because after each update you would need a new world, because everything will depend on world generation (abilities, recipes, armors, bosses, etc...)

**Comment by ghost** [comment] 2017-05-01 19:30
hmmm... can you add more structures such as the classic armorplus tower to the world generation please? i really like structures that spawns on the world generation ^^

**Comment by sokratis12GR** [comment] 2017-05-01 19:31
that is kind a the plan :) and more: https://www.reddit.com/r/feedthebeast/comments/61ti0c/new_blocks_for_the_upcoming_armorplus_update_more/

**Comment by ghost** [comment] 2017-05-01 19:33
nice to hear that

**Comment by sokratis12GR** [comment] 2017-05-04 10:08
Alright, after so many issues occurred for 1.11.2 ... I'm going to release a pre-change update fixing those :)

**Comment by ghost** [comment] 2017-05-04 10:57
Thanks. And we are waiting for more structures :)

**Comment by sokratis12GR** [comment] 2017-05-04 10:58
well, the upcoming update will have excluded some of the stuffs that this will be upcoming soon

**Comment by sokratis12GR** [comment] 2017-05-04 10:58
Its mainly just bug fixes and addition of #120

**Comment by ghost** [comment] 2017-05-04 16:05
ohh my god i'm so sorry, plz don't take care with my latest comment. i was just confused and thought it's ToroQuest mod xD sorry.
edit: i edited/fixed my comment.

**Comment by sokratis12GR** [comment] 2017-05-04 19:32
Fixed in [armorplus-1.11.2-10.2.0.1](https://minecraft.curseforge.com/projects/armorplus/files/2415900) :)

**Closed as completed by sokratis12GR** 2017-05-04 19:32 UTC
Labels: bug, question, 1.11.2

**Comment by ghost** [comment] 2017-05-04 19:40
thanks!
