### ISSUE TITLE
[1.11] Crafting Recipes Problem

### ISSUE THREAD

**Issue by LilShrimp01** [sokratis12GR/ArmorPlus#79] opened 2016-11-27 21:23 UTC
ArmorPlus Version: 1.11, 9.0.0.1, Alpha

TheDragonLib Version: 1.11, 2.0.1

MinecraftForge Version: 1.11, 13.19.0.2157

Minecraft Version: 1.11

Client or Server?: Client

Crash Report (via. Pastebin): Not a crash, a glitch.

What happens / happened?: The crafting recipes don't work. I tried making the armor with both the item's block or ingot/dust and it doesn't work. The armor itself is in the creative menu under "ARP Armors." Nothing crashes, just seems to be a glitch.

How can I reproduce it?: Use the mod versions above and try to craft them yourselves. It doesn't work for some reason.

(Optional) Mod List: ArmorPlus, Chameleon, Compatlayer, CxLibrary, EnderCompass, Endercrop, Forgelin, LiteralAscension, Llibrary, McJTYLib, MoreFurnances, NetherEssence, Optifine, Photoptics, Reliquary, RFTools, Stellar API, StorageDrawers, TheDragonLib, TreeChopper.

**Comment by sokratis12GR** [comment] 2016-11-27 22:00
Duplicate of #78

**Closed as completed by sokratis12GR** 2016-11-27 22:00 UTC
Labels: 1.11.2

**Comment by LilShrimp01** [comment] 2016-11-27 22:08
Ah, sorry to make that useless post, I literally didn't see the post before this one xD 
Does that mean next update there will be recipes or naw?

**Comment by sokratis12GR** [comment] 2016-11-27 22:10
1.11 is on currently on hold because of new major changes and new things that may may not come.
I'll be supporting only 1.10.2 for a while.
