### ISSUE TITLE
Server error for player just after getting Welcome to AP Achievement

### ISSUE THREAD

**Issue by BSKCraft** [sokratis12GR/ArmorPlus#116] opened 2017-03-10 01:01 UTC
**ArmorPlus Version**: 10.1.0.1

**TheDragonLib Version**: 3.1.1

**MinecraftForge Version**: 13.20.0.2253

**Minecraft Version**: 1.11.2

**Client or Server?**:
- [ ] Client
- [X ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: http://pastebin.com/7C1t6ixp

**What happens / happened?**: " I told ya I built the blue crafting table type thing put it down and crashed" - from the player himself

**How can I reproduce it?**: Craft and place a blue crafting table?

**(Optional) Mod List**: http://pastebin.com/cFDMqajA

**Comment by sokratis12GR** [comment] 2017-03-10 11:01
Duplicate of #115

**Closed as completed** 2017-03-12 12:17 UTC
Labels: bug, 1.11.2
