### ISSUE TITLE
[1.10.2] Client Crash

### ISSUE THREAD

**Issue by daanstout** [sokratis12GR/ArmorPlus#84] opened 2016-12-21 21:33 UTC
i got a client crash and posted it to /r/FTBCrashes and got redirected to here as it was said that it was because of ArmorPlus, i think it'll be easier to link the thread: https://www.reddit.com/r/FeedTheBeastCrashes/comments/5jkhe7/crash_with_custom_modpack_while_playing_on_a/

**Comment by sokratis12GR** [comment] 2016-12-21 21:50
Hey @maestroke thanks for the report. Could you provide me more a little more information or how I could reproduce it ?

**Comment by daanstout** [comment] 2016-12-21 22:16
i had the first crafting table of you guys, the blue 3x3 one, and a couple of blocks away the Immersive Engineering Coke Oven, after a while the coke oven would glitch and appear 5x5x5 instead of 3x3x3 and it eventually crashes the client. i'll grab some pictures of my setup and if i am lucky, of the bug itself

**Comment by daanstout** [comment] 2016-12-21 22:41
http://imgur.com/a/kSzdz
this time it happened with the blast furnace

**Comment by sokratis12GR** [comment] 2016-12-22 16:08
I need more information about the actual crash caused by the bench.
Well it might be a cross-mod incompatibility.
I'll keep this issue open.

**Comment by daanstout** [comment] 2016-12-22 16:43
this is all the info i have available. what exactly are you looking for? and it might take like 15-30 minutes for it to happen. could it help if i send you my world including the mods? basicly, the whole curse folder for the modpack?

**Comment by sokratis12GR** [comment] 2016-12-22 16:45
I'm looking on how to reproduce it so I'd try and find the issue and fix it :).
Sending the world and mods could help and should be the only thing needed

**Comment by daanstout** [comment] 2016-12-22 19:22
then i'll work on it tomorrow, already a bit late where i live

**Comment by daanstout** [comment] 2016-12-24 13:59
you can download the curse instance here: http://www.mediafire.com/file/ovu0266u0c1nt0o/Custom_1.10.2_modpack.7z
the world you can find the bug on is called "world". it took 36 minutes for the bug to happen, so you have to be patient. might take longer though

**Comment by daanstout** [comment] 2016-12-29 23:15
any luck?

**Comment by sokratis12GR** [comment] 2016-12-29 23:16
Going to test it tomorrow, didn't had time these days (vacation)

**Comment by daanstout** [comment] 2016-12-30 10:45
okay, good luck

**Comment by sokratis12GR** [comment] 2016-12-30 11:21
@maestroke Sorry, could you re-upload the instance but in .zip format ?
(current size is over 900mbs which for me takes around 10 hours of download time via my browser)

**Comment by daanstout** [comment] 2016-12-30 15:03
https://www.mediafire.com/?7hkb80dgjko438g

**Comment by sokratis12GR** [comment] 2017-01-05 12:49
Yeah I'm sorry I was unable to reproduce this issue.
Closing the issue

**Closed as completed by sokratis12GR** 2017-01-05 12:49 UTC
Labels: help wanted, 1.10.2, Under Review, Can't Reproduce
