### ISSUE TITLE
[1.12] 11.5.0.15-alpha Crash

### ISSUE THREAD

**Issue by JonL98** [sokratis12GR/ArmorPlus#165] opened 2017-08-08 19:15 UTC
**ArmorPlus Version**:
1.12-11.5.0.15-alpha
**TheDragonLib Version**:
1.12-4.1.0
**Forgelin Version**:
1.5.1
**MinecraftForge Version**:
1.12-14.21.1.2426
**Minecraft Version**:
1.12
**(Optional) Just Enough Items (JEI) Version**:

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://pastebin.com/zRBRBQwS
**What happens / happened?**:
Crash at game start/loadup
**How can I reproduce it?**:

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment] 2017-08-09 04:52
Duplicate of #163

**Closed as completed** 2017-08-09 21:34 UTC
Labels: bug, 3rd Part Mod Support, 1.12.2
