### ISSUE TITLE
[1.10.2] No more recipes in JEI

### ISSUE THREAD

**Issue by mcdodge34** [sokratis12GR/ArmorPlus#71] opened 2016-11-09 23:07 UTC
I keep everything up to date, I'm paranoid about incompatibility if something isn't updated, the only exception is Forge is 2122 otherwise I get a crash.

Latest version of JEI, Forge 2122, latest version of ArmorPlus and the library, I don't see any recipes besides the one to get the armor forge, and that's it.

**Comment by sokratis12GR** [comment] 2016-11-09 23:08
Duplicate of #69

**Closed as completed by sokratis12GR** 2016-11-09 23:08 UTC
Labels: bug, 1.10.2

**Comment by mcdodge34** [comment] 2016-11-09 23:11
I'm not crashing, at all like in #69 issue, just the recipes aren't there, I can see the items, but not their recipes.

**Comment by sokratis12GR** [comment] 2016-11-09 23:12
yes, #69 is for issues with jei versions until the update is released and if there are more issues after the update , please then create another issue for it.

**Comment by sokratis12GR** [comment] 2016-11-09 23:13
but for now it will be good to keep them all in one issue

**Comment by mcdodge34** [comment] 2016-11-09 23:14
Ok, I didn't read the issue at all, the first topic doesn't mention the problems I had, but now that I've read it, I'll wait for the fix version, I think we can still craft the stuff if we know their recipes so as long as I don't get a crash while crafting them, I'll be alright I guess.

**Comment by sokratis12GR** [comment] 2016-11-09 23:16
Recipes should work fine, just jei support is outdated
