### ISSUE TITLE
Cobalt armor does not provide any effects

### ISSUE THREAD

**Issue by Mac15001900** [sokratis12GR/ArmorPlus#225] opened 2019-06-07 15:53 UTC
**Affected Versions:**:
  - **ArmorPlus**: 11.23.0.59
  - **TheDragonLib**: 5.3.0
  - **Minecraft**: 1.12.2
  - **Forge**: 14.23.5.2838

**Affected Side (Client or Server)**:
- [X] Client
- [X] Server

**What happens**:
Basically, the same behaviour as in #204: equipping a full set of cobalt armor does not apply haste III.
A comment on #204 mentioned a fix would be available in 11.14.0.42, but the issue is still present in 11.23.0.59.
Other sets of armor seem to work properly.

**What you expected to happen:**:
For the armor to apply haste III.

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
The default config of Omnifactory (1.0.5). 
*The whole folder*: https://drive.google.com/uc?id=1bbanB9XCDiN8KTkILLYUQRVgUdpLRyRm
*Just registry.cfg*: https://pastebin.com/LF8E6Z3K

**Mod List**:
https://minecraft.curseforge.com/projects/omnifactory/relations/dependencies

**Comment by sokratis12GR** [comment] 2019-06-09 17:32
Cannot reproduce.

**Comment by sokratis12GR** [comment] 2019-06-09 17:51
Sorry I was wrong. Its a bug, will try to fix it asap.

**Comment by sokratis12GR** [comment] 2019-06-26 01:54
[ArmorPlus 1.12.2-11.24.0.60](https://minecraft.curseforge.com/projects/armorplus/files/2730003) should fix this issue, please close this issue if it is resolved.

**Closed as completed** 2019-06-26 18:05 UTC
Labels: bug, 1.12.2
