### ISSUE TITLE
Tinkers Tool Forge crashing

### ISSUE THREAD

**Issue by Gladi** [sokratis12GR/ArmorPlus#139] opened 2017-05-13 16:51 UTC
**ArmorPlus Version**: 10.3.0.1

**TheDragonLib Version**: 3.2.2

**MinecraftForge Version**: 13.20.0.2296

**Minecraft Version**:1.11.2

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
http://paste.feed-the-beast.com/view/ffbc3a03
**What happens / happened?**:
When putting a Tinker Tool into the Tinker Tool Forge the client crashes
removing armorplus solves this
Also see https://github.com/SlimeKnights/TinkersConstruct/issues/2903
**How can I reproduce it?**:
TConstruct 2.7.0.12 + Armor Plus 10.3.0.1 -> Put a Tinkers Tool into the Tool Forge

**(Optional) Mod List**:

**Comment by Wizardon777** [comment] 2017-05-13 17:46
I can confirm that the bug is not present in version 10.2.1.2 - only in 10.3.0.1

**Comment by sokratis12GR** [comment] 2017-05-13 17:53
Alright, thanks for the bug report will be fixed within the next 2 days (currently away from home) 
This is a bug due to the 1.10.2 - > 1.11.2 code port... 1 line has a null where it ain't supposed to have.

**Comment by sokratis12GR** [comment] 2017-05-15 15:34
Issue should be fixed, [armorplus-1.11.2-10.3.1.2](https://minecraft.curseforge.com/projects/armorplus/files/2420119).

**Closed as completed by sokratis12GR** 2017-05-15 15:34 UTC
Labels: bug, 1.11.2
