### ISSUE TITLE
[1.10.2] No recipes for armors via JEI

### ISSUE THREAD

**Issue by Sahidus** [sokratis12GR/ArmorPlus#61] opened 2016-10-01 21:56 UTC
**ArmorPlus Version**: Tried version 7 for 1.10.2, then downgraded to 6.0.9.2 with same result

**TheDragonCore Version**: 1.0.2.0

**MinecraftForge Version**: 12.18.1.2094

**Client or Server?**:
- [X] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: No crashes

**What happens / happened?**: None of the basic armors have recipes, only the extreme ones do. No JEI recipes and attempting to craft them in the Armor Forge is also unsuccessful.

**How can I reproduce it?**: Don't know. Have same set up as me and try it?

**(Optional) ModPack**: Personal mudpack that I made for myself; unpublished. Mod list as follows:
AppleCore
AppleSkin
ArmorPlus
Baubles
Better Builder's Wand
BetterBedrockGen
BetterFPS
Botania
Chameleon
Chisel
Clay Bucket
Cyclops Core
Druidry
Ender IO
Ender Zoo
EnderCore
EvilCraft
Excore
Extra Utilities
Extreme Reactors
EZStorage 2
Fast Leaf Decay
Forever Enough Items
Good ol' PVP
Good Old Backpacks
GraveStone Mod
Hardcore Questing Mode
InGame Info XML
Inventory Tweaks
IvToolkit
JEI Hider
JourneyMap
Just Enough Buttons
Just Enough Items (JEI)
Just Enough Resources (JER)
Just Jetpacks
LootBags
LunatriusCore
Lycanite Mobs
Mantle
Mekanism
MekanismTools
Minecraft Comes Alive
Mouse Tweaks
Natura
Nether Metals
Netherrocks
OpenBlocks Elevator
Pam's Clay Spawn
Pam's HarvestCraft
Pandora's Box
Power Apples
RadixCore
Random Things
Realistic Terrain Generation
Roguelike Dungeons
ShadowMC
Simple Tcon
SimpleCore API
SimpleHarvest
Sleeping Bag
stimmedcow: NoMoreRecipeConflict
Storage Drawers
TheDragonCore
Tinkers Construct
Tinkers' Addons
Tinkers; Tool Leveling
TrashSlot
VeinMiner
Waila
Waila Harvestability
ZeroCore

**Comment by sokratis12GR** [comment] 2016-10-01 21:58
if you use TheDragonCore 1.10.2-1.0.2.0 you need to use ArmorPlus 1.10.2-7.0.0.0 in order to work, all the recipes should work unless you have an old config file that has conficts or:
JEI version ?

**Comment by kwpugh** [comment] 2016-10-02 01:51
I have dragon core 1.0.2.0 and armor plus 7.0.0.0 with default new config files on both client and server, no receipes for armor forge items (armor, etc.) except the advanced armor forge shows just the recipe for ultimate armor pieces.

**Comment by sokratis12GR** [comment] 2016-10-02 07:55
default config is expert mode, have you tried using those recipes ?
https://ftb.gamepedia.com/ArmorPlus
- There is no possibility for the recipes to not work, because if the Advanced Armor Forge ones work, the normal ones must work.

**Comment by Sahidus** [comment] 2016-10-02 14:45
What's with the "not a bug"? It is clearly a bug, and you can't say "there is no chance" when there clearly IS a chance. Advanced works, basic does not work. Boooo and thumbs down on the support. I put way more effort than that to report it than you have made in resolving this.

**Comment by sokratis12GR** [comment] 2016-10-02 14:50
@Sahidus "Not a bug" - is a label that is added to the issue, until its a proved a bug
You could help me resolve it if you provide me me some more information that "recipes don't work"
It would also help if you could provide a link to where I can download the modpack to see if its a mod conflict (I only need config folder wither the configs and mods folder with the mods).
Also providing JEI version will help, since it might only be not showing up on the recipes list, thanks

**Comment by sokratis12GR** [comment] 2016-10-02 14:52
Also could you specify which armor's recipes didn't work.

**Comment by Sahidus** [comment] 2016-10-02 15:44
All mods are up to date, including JEI. Still doesn't work. You can download the entire mudpack at www.plarium.club/MN1.zip

**Comment by sokratis12GR** [comment] 2016-10-02 15:45
the current version of ArmorPlus doesn't work with the latest JEI #58

**Comment by sokratis12GR** [comment] 2016-10-02 15:46
Also the url is invalid you provided me is invalid

**Comment by Sahidus** [comment] 2016-10-02 15:46
Apologies, that's only accessible to me. You can download it at http://plariumonline.ipage.com/MN1.zip

**Comment by Sahidus** [comment] 2016-10-02 15:47
If I need a specific version of JEI, please specify which version it is so I can downgrade my JEI.

**Comment by sokratis12GR** [comment] 2016-10-02 15:49
Duplicate of #58

**Comment by Sahidus** [comment] 2016-10-02 15:52
That is MANY versions back, and now Ender IO has to be downgraded as it doesn't work with that version of JEI.

**Comment by sokratis12GR** [comment] 2016-10-02 15:53
I'm sorry but thats because JEI updates frequently, and I'm working on a coming soon update that will support the current latest version of JEI

**Comment by Sahidus** [comment] 2016-10-02 16:11
Downgrading the JEI to that version and downgrading Ender IO to match resolved the issue, recipes now work. But I am certain there is countless people out there who have one of the 10 versions of JEI above the one you specified, so just know that the issue is real and it is due to the incompatibility with newer JEI versions. The issue is resolved as far as I am concerned, so I can finally give your mod a proper chance.

**Comment by sokratis12GR** [comment] 2016-10-02 16:12
I know this, thats why I have warned people that things wont work in latest versions

**Comment by sokratis12GR** [comment] 2016-10-02 16:12
![image](https://cloud.githubusercontent.com/assets/12274096/19021894/3525be42-88d4-11e6-858a-045245defae9.png)

**Comment by sokratis12GR** [comment] 2016-10-02 16:15
Not certanly a crash but things work work and the thing is that the 10 newer versions were created in a period of some days, meanwhile ArmorPlus was supposting the latest one at the time it was 7.0.0.0 released. 
these issues will be fixed in the coming soon update
#58 , #59

**Comment by sokratis12GR** [comment] 2016-10-02 16:15
https://github.com/TheDragonTeam/ArmorPlus/blob/1.10.2/github-changelogs.md#armorplus-1102-70103-dev This issue was fixed on a dev version, soon released on curse

**Comment by ldittmar81** [comment] 2016-10-11 07:15
Soon means?? Maybe this weekend, because I have holidays next week?? Please... :smile:

**Comment by sokratis12GR** [comment] 2016-10-11 07:16
Probably near the end of this weekend

**Comment by sokratis12GR** [comment] 2016-10-11 07:16
I have to do some more testing

**Comment by ldittmar81** [comment] 2016-10-11 07:19
That would be cool, but you can also release a beta version. There are certainly many people who would like to help you with the testing. :wink:

**Comment by Morpheus1101** [comment] 2016-10-11 07:20
I can assure you testing has all ready occurred on said versions

**Comment by sokratis12GR** [comment] 2016-10-11 07:24
https://github.com/TheDragonTeam/ArmorPlus/blob/1.10.2/github-changelogs.md#armorplus-1102-70101-dev

**Comment by sokratis12GR** [comment] 2016-10-13 16:38
Fixed in 1.10.2-7.0.1.0.5

**Closed as completed by sokratis12GR** 2016-10-13 16:38 UTC
Labels: bug, 1.10.2
