### ISSUE TITLE
Game crash en load a World

### ISSUE THREAD

**Issue by Switch-Back18** [sokratis12GR/ArmorPlus#243] opened 2021-01-10 12:39 UTC
**Affected Versions (Do not use "latest"):**:
  - **ArmorPlus**:16.2.1
  - **TheDragonLib**:1.1.0
  - **Minecraft**:1.16.4
  - **Forge**: 35.1.36
  - (Optional) Just Enough Items (JEI):7.6.1.65
  - (Optional) CraftTweaker (CrT):7.1.0.79

**Affected Side (Client or Server)**:
- [x] Client
- [x] Server

**What happens**:
When i create a new World the game crash, only when i add armorplus

**What you expected to happen:**:
I just want to create a new World and play

**If its a crash, post your crash report (via. pastebin/gist/etc)**:

https://hastebin.com/tuquritipo.rb

**Your configuration files from `config/armorplus/` (`registry.cfg` mainly)**:
Nothing changed

**(Optional) Mod List**:
https://hastebin.com/ohelovobin.apache

**Comment by sokratis12GR** [comment] 2021-01-10 12:39
Do you have Geckolib 3 installed ?

**Comment by Switch-Back18** [comment] 2021-01-10 12:39
Yes of course

**Comment by sokratis12GR** [comment] 2021-01-10 12:41
Interesting, seems to be an issue connected to TombStone & Minecolonies, not sure how it affects ArmorPlus though

**Comment by Switch-Back18** [comment] 2021-01-10 12:42
Yes, i see that too and i don't know why that very werd

**Comment by sokratis12GR** [comment] 2021-01-10 12:43
Alright, this shouldn't be happening. Will investigate and once I find the issue will release a fix. Thanks for the report!

**Comment by Switch-Back18** [comment] 2021-01-10 12:46
Thank you, Have a good day !

**Comment by sokratis12GR** [comment] 2021-01-10 14:39
This issue should be fixed. Please confirm.

[1.16.3-16.2.2](https://www.curseforge.com/minecraft/mc-mods/armorplus/files/3164140)

**Comment by Switch-Back18** [comment] 2021-01-10 14:46
That not fixed

**Comment by sokratis12GR** [comment] 2021-01-10 14:47
Could you send the new crash report over?

**Comment by Switch-Back18** [comment] 2021-01-10 14:48
https://hastebin.com/ujojafumur.rb

**Comment by sokratis12GR** [comment] 2021-01-10 15:35
Alright could you please try again with [1.16.3-16.2.3](https://drive.google.com/file/d/1PVg8GVbxeV2zwdniLdXiPGUwzfcxp-Lx/view?usp=sharing) and let me know the result ?

**Comment by Switch-Back18** [comment] 2021-01-10 15:44
https://hastebin.com/azuwiwuwiv.rb

**Comment by sokratis12GR** [comment] 2021-01-10 16:07
I'm afraid I cannot reproduce the issue after version 16.2.2
Would it be possible to try and see if the issue persists on a new world ?

**Comment by Switch-Back18** [comment] 2021-01-10 17:23
I try now

**Comment by Switch-Back18** [comment] 2021-01-10 17:32
That not works https://hastebin.com/oquxedamex.rb

**Comment by sokratis12GR** [comment] 2021-01-10 17:38
I'm really lost, as there shouldn't be any issue with the entities.
Some other mod is messing with the entities and invalidates mine. Which is rather interesting as I tested with the provided mods on, and there were no issues.

**Comment by Switch-Back18** [comment] 2021-01-10 17:40
You try with all mods in the crash ?

**Comment by sokratis12GR** [comment] 2021-01-10 17:41
I've tried with the ones that were listed on the crash report itself
Tombstone
Reliquery

**Comment by Switch-Back18** [comment] 2021-01-10 17:41
There is Minecolonies too

**Comment by Switch-Back18** [comment] 2021-01-10 17:41
CompatibilityMinecolonies.isCitizen(CompatibilityMinecolonies.java:28)

**Comment by sokratis12GR** [comment] 2021-01-10 17:42
Hmm right, will try with minecolonies as well, seems to be the core of the issue then.

**Comment by Switch-Back18** [comment] 2021-01-10 17:48
I tried without Minecolonies and that works, the problem is with ArmorPlus and Minecolonies

**Comment by sokratis12GR** [comment] 2021-01-10 17:54
Could you test minecolonies (and its dependencies) with just A+ (and its dependencies) and send over the crash report if that's the case ?

**Comment by Switch-Back18** [comment] 2021-01-10 18:02
I have tried with A+ and Minecolonies, that works
I have add Tombstone that works
I have add Reliquary that crashed

**Comment by Switch-Back18** [comment] 2021-01-10 18:03
https://hastebin.com/opitozebiw.properties

**Comment by Switch-Back18** [comment] 2021-01-10 18:04
the crash name is crash-2021-01-10_19.02.40-server 
Is server-side i think

**Comment by sokratis12GR** [comment] 2021-01-10 18:06
Alright time for a weird test, try downgrading tombstones to [Corail Tombstone 3.6.8](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/files/2885466). This might work with them all installed.

**Comment by Switch-Back18** [comment] 2021-01-10 18:07
It's an 1.12 version

**Comment by sokratis12GR** [comment] 2021-01-10 18:09
Oops wrong one, I meant to send this one: [Corail Tombstone 6.1.0](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/files/3136695)

**Comment by Switch-Back18** [comment] 2021-01-10 18:23
That works

**Comment by sokratis12GR** [comment] 2021-01-10 18:24
Awesome, seems to be all connected to the tombstone minecolonies method added in later versions. There is nothing I can do on my side, I'd suggest either using an older version of their mod or removing one of the mods. Thanks for your help figuring this out and have a great day!

**Closed as completed by sokratis12GR** 2021-01-10 18:24 UTC
Labels: Can't Reproduce, 1.16.3, Should be fixed
