### ISSUE TITLE
[1.9.4] Crash during Forge loading

### ISSUE THREAD

**Issue by bignate1011** [sokratis12GR/ArmorPlus#46] opened 2016-07-22 01:59 UTC
ArmorPlus 1.9.4-4.1.7.1

Forge 12.18.1.2014

**Client or Server?**: SSP World

Crash Report http://pastebin.com/buHTjUkw

What happens / happened?: Game crashing on startup after updating. Disabling ArmorPlus allows me to start up.

How can I reproduce it?: Start game after updating

**Comment by sokratis12GR** [comment] 2016-07-22 05:30
Duplicate of #45

**Comment by sokratis12GR** [comment] 2016-07-22 05:39
Fixed in version 1.9.4-4.1.7.2

**Comment by sokratis12GR** [comment] 2016-07-22 06:54
1.9.4-4.1.7.2

**Closed as completed by sokratis12GR** 2016-07-22 06:54 UTC
Labels: bug, 1.9.4
