### ISSUE TITLE
[1.12] Crashes With Latest Forge

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#154] opened 2017-06-25 17:11 UTC
[crash-2017-06-25_20.10.12-client.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1100484/crash-2017-06-25_20.10.12-client.txt)

**Comment by sokratis12GR** [comment] 2017-06-25 22:16
sooo, lets see if its a "disabling" an item from the game crash again xD...

**Comment by IchigoGames** [comment] 2017-06-29 18:09
yap same thing happend to me

**Comment by sokratis12GR** [comment] 2017-06-30 05:12
Okay, I'll need a little bit more info:
* ArmorPlus' Config

**Comment by CluelessPhil** [comment] 2017-06-30 05:38
Same issue here:

java.lang.NullPointerException: Can't use a null-name for the registry, object null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:267)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:261)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:105)
	at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:146)
	at net.thedragonteam.armorplus.events.RegistryEventHandler.registerItems(RegistryEventHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_129_RegistryEventHandler_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:691)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:671)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Migmag789** [comment] 2017-06-30 15:45
How to fix it ?

**Comment by sokratis12GR** [comment] 2017-06-30 15:46
Working on it :)

**Comment by Moritz30** [comment] 2017-06-30 15:46
Not using the latest forge until we made a fix

**Comment by Migmag789** [comment] 2017-06-30 15:49
Which version am I supposed to use?

**Comment by sokratis12GR** [comment] 2017-06-30 15:50
1.12 is currently broken, will be releasing an update within a few hours/minutes

**Comment by Migmag789** [comment] 2017-06-30 15:52
Ok, thx

**Comment by sokratis12GR** [comment] 2017-06-30 20:10
ArmorPlus [1.12-11.3.0.7-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2443995) should have fixed this issue, please let me know! :)

**Comment by PenguinRage78** [comment] 2017-07-01 01:57
Latest still crashes on launch for me.  

Here's the top of the stack:

Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at net.thedragonteam.armorplus.blocks.base.BlockBase.<init>(BlockBase.kt)
	at net.thedragonteam.armorplus.blocks.base.BlockBase.<init>(BlockBase.kt:12)
	at net.thedragonteam.armorplus.blocks.base.BlockBase.<init>(BlockBase.kt)
	at net.thedragonteam.armorplus.blocks.lava.OreLavaCrystal.<init>(OreLavaCrystal.java:35)
	at net.thedragonteam.armorplus.registry.ModBlocks.<clinit>(ModBlocks.java:31)
	at net.thedragonteam.armorplus.proxy.CommonProxy.preInit(CommonProxy.java:30)
	at net.thedragonteam.armorplus.proxy.ClientProxy.preInit(ClientProxy.java:22)
	at net.thedragonteam.armorplus.ArmorPlus.preInit(ArmorPlus.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by sokratis12GR** [comment] 2017-07-01 07:58
@PenguinRage78 do you have forgelin 1.5.0 installed ?

**Comment by PenguinRage78** [comment] 2017-07-02 19:50
Well that's embarrassing, I missed the forgelin download.  All good now.

**Comment by ghost** [comment] 2017-07-02 20:18
plz add forgelin mod check such as thedragonlib

**Comment by sokratis12GR** [comment] 2017-07-02 20:22
going to, soon (currently away from home for a few days)

**Comment by sokratis12GR** [comment] 2017-07-02 20:22
so what is the status of the issue ?
* Resolved
or
* Still crashing

**Comment by ghost** [comment] 2017-07-02 20:23
will try again plz keep it open for 1 more day

**Comment by sokratis12GR** [comment] 2017-07-02 20:24
No worries

**Comment by ghost** [comment] 2017-07-03 17:36
hey sokratis, it crashes on world creation.

**Comment by ghost** [comment] 2017-07-03 17:37
[crash-2017-07-03_20.37.39-server.txt](https://github.com/TheDragonTeam/ArmorPlus/files/1120248/crash-2017-07-03_20.37.39-server.txt)

**Comment by sokratis12GR** [comment] 2017-07-05 10:39
Okay, I'm so damn confused... I don't get the error... I have made sure everything is how it should be... Like wtf.. I really need some help on this one, because this shouldn't have happened even on the older version... It works 100% In dev environment and servers I have tested... I can't find the issue :/

**Comment by ghost** [comment] 2017-07-05 10:43
ill help u after 10 mins give me a little bit time

**Comment by ghost** [comment] 2017-07-05 11:26
oh, i dont know why but it doesn't happen anymore. (using forge 2396)

**Comment by sokratis12GR** [comment] 2017-07-05 12:57
I need at least a few more confirmations that this is fixed with latest forge,  A+, tdl

**Comment by ghost** [comment] 2017-07-05 15:23
i will make more tests today.

**Comment by sokratis12GR** [comment] 2017-07-15 14:00
Guys let me know if this version works as intened https://minecraft.curseforge.com/projects/armorplus/files/2451023
Requires:
* TheDragonLib 1.12-4.1.0 or later
* Forgelin
* Forge 14.21.1.2412 or later

**Comment by sokratis12GR** [comment] 2017-07-16 07:17
As people were able to test and play in the latest version I consider this as resolved (if its not create a new issue please).
[ArmorPlus 1.12-11.3.4.11-alpha](https://minecraft.curseforge.com/projects/armorplus/files/2451414) Should have this issue fixed

**Closed as completed by sokratis12GR** 2017-07-16 07:17 UTC
Labels: bug, 1.12.2
