### ISSUE TITLE
[1.11.2] java.lang.NullPointerException: Unexpected error armorplus-1.11.2-9.5.4.5-beta (More bow problems)

### ISSUE THREAD

**Issue by SDUBZ** [sokratis12GR/ArmorPlus#98] opened 2017-02-05 13:10 UTC
**ArmorPlus Version**:
armorplus-1.11.2-9.5.4.5-beta
**TheDragonLib Version**:
thedragonlib-1.11.2-2.2.3
**MinecraftForge Version**:
1.11.2-2226
**Minecraft Version**:
1.11.2
**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
[crash-2017-02-06_00.02.19-client.txt](https://github.com/TheDragonTeam/ArmorPlus/files/752977/crash-2017-02-06_00.02.19-client.txt)
fml client latest:
[fml-client-latest.txt](https://github.com/TheDragonTeam/ArmorPlus/files/752982/fml-client-latest.txt)

**What happens / happened?**:
was fighting end dragon testing stabability of the end and it shutdown and crashed me back to desktop
**How can I reproduce it?**:
have a ender bow and ender arrows and fight the ender dragon
**(Optional) Mod List**:
[print.txt](https://github.com/TheDragonTeam/ArmorPlus/files/752981/print.txt)

**Comment by sokratis12GR** [comment] 2017-02-05 13:14
how did it crash ?
When you tried to shot it with the bow or when killed it ?

**Comment by sokratis12GR** [comment] 2017-02-05 13:15
Duplicate of #90

**Comment by SDUBZ** [comment] 2017-02-05 13:22
it happend when i was fighting the enderdragon and got it down to about 50% and going for a another shot and then crash

**Comment by sokratis12GR** [comment] 2017-02-05 13:23
did you run out of arrows or ?

**Comment by SDUBZ** [comment] 2017-02-05 13:23
i was testing creative

**Comment by sokratis12GR** [comment] 2017-02-05 13:23
oh creative, that changes everything

**Comment by sokratis12GR** [comment] 2017-02-05 13:23
does the issue happen when you are on survival ?

**Comment by SDUBZ** [comment] 2017-02-05 13:24
umm not sure id have to cheat myself some OP armor then try again

**Comment by SDUBZ** [comment] 2017-02-05 13:26
i will test more when i get up okay after the tech comes fixes my net so it will have to be after that

**Comment by sokratis12GR** [comment] 2017-02-05 14:42
This issue is hopefully fixed in the [armorplus-1.11.2-9.5.5.6-beta](https://minecraft.curseforge.com/projects/armorplus/files/2378145) version.

**Closed as completed by sokratis12GR** 2017-02-05 14:42 UTC
Labels: bug, 1.11.2
